In [40]:
import numpy as np
import numpy.testing as npt
from scipy.linalg import expm
import matplotlib.pyplot as plt
import scipy.spatial, scipy.linalg
from scipy.spatial.distance import pdist
import scipy.sparse.linalg
from scipy.linalg import eigh
import zipfile,io
import pandas as pd
import zipfile
import re
import time
import numpy as np
import matplotlib.pyplot as plt
import time
import itertools as it
%matplotlib inline

# K-means Clustering

In this problem set we will implement and apply the standard (batch) K-means algorithm, the online version, and the “soft” clustering procedures. The file cluster.dat contains a data set of p = 500 (2-dimensional) observations generated from four different Gaussians with four different means.

## 9.1 K-means Clustering

Write a program that implements the standard version of K-means clustering and partitions the given data set into K clusters. Repeat the clustering procedure for different initializations of the prototypes and K = 2, 3, 4, 5, 6, 7, 8. Include the following steps:

### Initialization –

• Set the initial prototypes wq randomly around the data set mean

• Set the maximum number of iterations tmax, e.g. 5


### Optimization –

Implement the k-means update (see lecture notes). Each iteration should contain the following two steps

• assign all datapoints to their closest prototype

• re-compute the new positions of the prototypes for this assignment


### Visualization –

(a) Visualize data points and prototypes for each iteration in a sequence of scatter plots.

(b) Plot the error function E against the iteration number t

(c) Create a plot (Voronoi-Tesselation) to show how the resulting solution assigns different regions of input space (e.g. new data points x 2 R2) to the different clusters.

In [41]:
dat=np.loadtxt("cluster.dat")

In [42]:
K = [2, 3, 4, 5, 6, 7, 8]
t_max= 5

In [52]:
def stdKmean(dat,K,t_max):
    n=len(dat[0])
    M = []
    W=[]
    k_ite=0
    for k in K:
        # Initializaton for each k
        w= np.random.randn(2,k)+np.mean(dat,1).reshape(2,1)
        X2 = (dat.T**2).sum(1).reshape(n,1)*np.ones((n,k))
        U2 = (w.T**2).sum(1).reshape(1,k) * np.ones([n,k])
        D = X2 - 2*(dat.T.dot(w)) + U2
        minidx= np.argmin(D,1)
        m = np.zeros((n,k))
        m[np.arange(n),minidx]=1
        W += [w]
        M += [m]
        for t in range(t_max):
            w = dat.dot(m)/m.sum(0)
            X2 = (dat.T**2).sum(1).reshape(n,1)*np.ones((n,k))
            U2 = (w.T**2).sum(1).reshape(1,k) * np.ones([n,k])
            D = X2 - 2*(dat.T.dot(w)) + U2
            minidx= np.argmin(D,1)
            m = np.zeros((n,k))
            m[np.arange(n),minidx]=1   
            M[k_ite]= m
            W[k_ite]= w
        k_ite +=1
    return M, W

In [53]:
def E(X,w,m):
    n=len(K[0])
    k = len(w[0])
    X2 = (X.T**2).sum(1).reshape(n,1)*np.ones((n,k))
    U2 = (w.T**2).sum(1).reshape(1,k) * np.ones([n,k])
    D = X2 - 2*(X.T.dot(w)) + U2
    return (D*m).sum()/(2*n)
    

In [54]:
#optimization 
M,W=stdKmean(dat,K,t_max)

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:18: RuntimeWarning: invalid value encountered in true_divide


In [ ]:
plt.figu
for k in K:
    plt.plot()

In [7]:
a=np.random.randn(5,5)
a

array([[ 0.86208328,  0.64249455, -1.22716098,  1.3668585 , -1.5962294 ],
       [ 0.71492158,  0.08128397,  1.4718968 , -1.2629766 ,  0.38980068],
       [ 1.18698704, -1.89514606, -0.78827458,  0.36856575,  1.17577916],
       [-0.93414087,  1.02206442, -0.14352597, -1.01765687, -0.87918478],
       [ 1.79988556, -1.56765357, -0.6612484 , -1.26093493, -0.3573135 ]])

In [9]:
b=np.argmin(a,1)
b

array([4, 3, 1, 3, 1])

In [13]:
c=np.zeros((5,5))
c[np.arange(5),b]=1

In [19]:
np.ones((2,5))/(np.ones(5)*2)

array([[ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5]])

In [20]:
mmm = []

In [27]:
mmm=mmm+[np.ones((2,2))]+[np.ones((4,4))]

In [34]:
mmm+= [np.zeros((6,6))]

In [36]:
mmm[0]=np.zeros((2,2))

In [37]:
mmm

[array([[ 0.,  0.],
        [ 0.,  0.]]), array([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]), array([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]])]